name: "Build"
on: [push, pull_request]
jobs: 
  pre:
    runs-on: nicolas-pc
    steps:
      - name: install
        run: apt-get install vim
      - name: Publish
        run: vim --version
  post:
    runs-on: nicolas-pc
    needs: pre 
    steps:
      - name: test
        run: vim --version
