name: "Build"
on: [push, pull_request]
jobs: 
  pre:
    runs-on: self-hosted
    steps:
      - name: distro
        run:  cat /etc/*-release
      - name: install
        run: echo "NOT ISOLATED" > ~/.prove
  post-1:
    runs-on: self-hosted
    steps:
      - name: test
        run: cat ~/.prove
  post:
    runs-on: self-hosted
    needs: pre 
    steps:
      - name: test
        run: cat ~/.prove
