name: "Build"
on: [push, pull_request]
jobs: 
  pre:
    runs-on: self-hosted
    steps:
      - name: distro
        run:  cat /etc/*-release
      - name: install
        run: apt-get install vim
      - name: Publish
        run: vim --version
  post:
    runs-on: self-hosted
    needs: pre 
    steps:
      - name: test
        run: vim --version
