name: "Build"
on: [push, pull_request]
jobs: 
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build . -t nicolaspascual/gh-actions:${{ github.sha }}
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nicolaspascual/gh-actions:${{ github.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

